# This is a basic workflow to help you get started with Actions

name: Linuxfix?

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildAndroid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.1.5
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib
        run: |
          sudo apt-get install gcc-multilib g++-multilib -y
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel 4.11.0
          haxelib run lime setup
          haxelib run lime setup flixel
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install newgrounds
          haxelib install flixel-addons
          haxelib install actuate 
          haxelib git polymod https://github.com/MasterEric/polymod.git --quiet
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git extension-webm https://github.com/KadeDev/extension-webm
          haxelib run lime rebuild extension-webm linux
          haxelib git newgrounds https://github.com/Geokureli/Newgrounds.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git linc_luajit https://github.com/MAJigsaw77/linc_luajit
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib list

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compile
        run: haxelib run lime build linux -debug

      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: LinuxBuild
          path: export/release/linux/bin
